version: '3'

services:
  nginx:
    depends_on:
      - react-front-main
      - express-server-main
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
  react-front-main:
    build: 
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - '3000:3000'
    restart: on-failure
  express-server-main:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - '5000:5000'
    restart: on-failure
  #certbot:
  #  image: certbot/certbot
  #  restart: unless-stopped
  #  volumes:
  #    - ./nginx/certbot/conf:/etc/letsencrypt
  #    - ./nginx/certbot/www:/var/www/certbot
    
networks:
  default:
    external:
      name: nginx-proxy